name: example-basic

on:
  push:
    paths:
      - "index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          file: "index.html"
